### PR TITLE
Updated ConfigureDialog

### PR DESCRIPTION
**Pull request by jnphilipp**
I updated the ConfigureDialog interface and added a few new options.

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Thanks!
I want to merge, but there are conflicts.
Would you mind fixing the conflicts so that I can merge?
Cheers,
Nicolas

**Comment by nicolas-raoul** [comment]
I just created an organization, that will be easier for collaboration :-)
You should be able to modify the code directly now, without sending me pull requests.

**Comment by jnphilipp** [comment]
It seems that I don't have write access.

**Comment by nicolas-raoul** [comment]
Sorry, how about now?

**Comment by jnphilipp** [comment]
The merge is done. The turkisch and russian translation aren't complete.

**Pull request merged**
